#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use PhpGpio\Gpio;

// $arguments_count = (int)$argc;
// echo "$arguments_count\n";

// $pin_count = $arguments_count - 1;
// $sleep_argument = $pin_count;

// for ($i = 1; $i < ($pin_count); $i++) {
// 	echo 'count';
// 	$pin[$i] = (int)stripslashes($argv[$i]);

// }

// $sleep_time_received = stripslashes($argv[$sleep_argument]);
// $sleep_time = (int)$sleep_time_received;


//$pin = (int)stripslashes($argv[1]);

$pin[0] = 17;
$pin[1] = 27;
$pin_count = count($pin);
//$sleep_time = (int)stripslashes($argv[2]);
$sleep_time = 3;

echo "Setting up pin 17\n";
$gpio = new GPIO();
for ($i = 1; $i <= $pin_count; $i++) {

	$gpio->setup($pin[$i-1], "out");

}


echo "Turning on pin 17\n";

for ($i = 1; $i <= $pin_count; $i++) {

	$gpio->output($pin[$i-1], 1);

}
echo "Sleeping!\n";
sleep($sleep_time);

echo "Turning off pin 17\n";
for ($i = 1; $i <= $pin_count; $i++) {

	$gpio->output($pin[$i-1], 0);

}

echo "Unexporting all pins\n";
$gpio->unexportAll();
