#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use PhpGpio\Gpio;


//maybe some verification that there are 2 arguments and the first is an array

$pin = unserialize($argv[1]);

$pin_count = count($pin);
$sleep_time = (int)stripslashes($argv[2]);

echo "Setting up pin 17\n";
$gpio = new GPIO();
for ($i = 1; $i <= $pin_count; $i++) {

	$gpio->setup($pin[$i-1], "out");

}


echo "Turning on pin 17\n";

for ($i = 1; $i <= $pin_count; $i++) {

	$gpio->output($pin[$i-1], 1);

}
echo "Sleeping!\n";
sleep($sleep_time);

echo "Turning off pin 17\n";
for ($i = 1; $i <= $pin_count; $i++) {

	$gpio->output($pin[$i-1], 0);

}

echo "Unexporting all pins\n";
$gpio->unexportAll();
